import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import NextTopLoader from "nextjs-toploader";
import { GoogleAnalytics, GoogleTagManager } from '@next/third-parties/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-N8N4T4Z8" />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GoogleAnalytics gaId="G-7TXR2L5D2J" />
        <Toaster
          toastOptions={{
            style: {
              fontSize: '0.6rem'
            },
          }}
        />
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
