// 100 Random motivational quotes for modal
export const motivationalQuotes = [
  "Crafted with ❤️ for better business.",
  "Built with passion for your success. 💼",
  "Made with love for amazing results. ❤️",
  "Designed to boost your productivity. 🚀",
  "Created with care for your growth. 🌱",
  "Built with dedication for great achievements. ⭐",
  "Made with purpose for your journey. 🎯",
  "Designed with love for better outcomes. 💪",
  "Crafted with heart for stellar results. ✨",
  "Built with vision for your dreams. 🌟",
  "Made with excitement for new beginnings. 🎉",
  "Designed with enthusiasm for success. 🔥",
  "Created with optimism for bright future. ☀️",
  "Built with determination for greatness. 🏆",
  "Made with creativity for innovation. 💡",
  "Designed with ambition for progress. 📈",
  "Crafted with patience for excellence. 🎖️",
  "Built with perseverance for victory. 🏅",
  "Made with courage for challenges. 💪",
  "Designed with wisdom for decisions. 🧠",
  "Created with kindness for community. 🤝",
  "Built with integrity for trust. 🔐",
  "Made with respect for relationships. 💕",
  "Designed with honesty for transparency. 📋",
  "Crafted with loyalty for partnership. 🤗",
  "Built with commitment for results. 🎯",
  "Made with focus for achievement. 🎯",
  "Designed with discipline for success. 📊",
  "Created with innovation for tomorrow. 🔮",
  "Built with resilience for adversity. 🛡️",
  "Made with gratitude for blessings. 🙏",
  "Designed with joy for happiness. 😊",
  "Crafted with hope for tomorrow. 🌅",
  "Built with confidence for greatness. 💎",
  "Made with passion for excellence. 🌟",
  "Designed with determination to win. 🏁",
  "Created with spirit for adventure. 🧭",
  "Built with imagination for possibilities. 🌈",
  "Made with perseverance never to give up. 🔥",
  "Designed with purpose for meaning. 🎯",
  "Crafted with love for humanity. 🌍",
  "Built with care for everyone. 💝",
  "Made with respect for all. 🕊️",
  "Designed with empathy for understanding. 💭",
  "Created with compassion for others. ❤️",
  "Built with generosity for giving. 🎁",
  "Made with humility for growth. 🌱",
  "Designed with courage to try. 🦁",
  "Crafted with strength to endure. 🏔️",
  "Built with patience to wait. ⏳",
  "Made with wisdom to choose. ⚖️",
  "Designed with clarity to see. 👁️",
  "Created with insight to understand. 🧩",
  "Built with talent to create. 🎨",
  "Made with skill to deliver. 🛠️",
  "Designed with expertise to excel. 📚",
  "Crafted with knowledge to share. 📖",
  "Built with experience to guide. 🧭",
  "Made with insight to lead. 🌟",
  "Designed with vision to dream. 💭",
  "Created with purpose to achieve. 🎯",
  "Built with goals to reach. 🎯",
  "Made with plans to succeed. 📋",
  "Designed with strategies to win. 🏆",
  "Crafted with actions to do. ✅",
  "Built with efforts to try. 💪",
  "Made with hard work to grow. 🌱",
  "Designed with dedication to improve. 📈",
  "Created with commitment to finish. 🏁",
  "Built with persistence to continue. 🔄",
  "Made with motivation to rise. ⬆️",
  "Designed with inspiration to act. ⚡",
  "Crafted with energy to move. 🏃",
  "Built with momentum to push. 🚀",
  "Made with drive to succeed. 💼",
  "Designed with ambition to excel. 🌟",
  "Created with hunger to learn. 📚",
  "Built with curiosity to explore. 🔍",
  "Made with wonder to discover. ✨",
  "Designed with awe to appreciate. 🌸",
  "Crafted with beauty to enjoy. 🌺",
  "Built with harmony to balance. ⚖️",
  "Made with peace to relax. 🧘",
  "Designed with joy to celebrate. 🎊",
  "Created with fun to laugh. 😂",
  "Built with love to live. ❤️",
  "Made with hope to dream. 💫",
  "Designed with faith to believe. ✝️",
  "Crafted with trust to rely. 🤝",
  "Built with confidence to try. 💪",
  "Made with courage to act. 🦸",
  "Designed with strength to help. 🤝",
  "Created with kindness to care. 💖",
  "Built with compassion to support. ❤️‍🩹",
  "Made with empathy to understand. 💝",
  "Designed with generosity to give. 🎁",
  "Created with love to share. 💕",
  "Built with care to protect. 🛡️",
  "Made with respect to honor. 🙏",
  "Designed with gratitude to thank. 🙌",
  "Built with joy to spread. 😊",
  "Made with peace to share. 🕊️",
];

// Function to get random quote
export const getRandomQuote = () => {
  const randomIndex = Math.floor(Math.random() * motivationalQuotes.length);
  return motivationalQuotes[randomIndex];
};
